version: "3.8"

services:
  backend:
    image: backend:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  frontend:
    image: frontend:latest
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:5000
